services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: servicesdashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d servicesdashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

  servicesdashboard:
    build:
      context: ./ServicesDashboard
      dockerfile: Dockerfile.dev
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
      - ConnectionStrings__DefaultConnection=Host=database;Database=servicesdashboard;Username=admin;Password=admin123
    command: ["dotnet", "watch", "run", "--urls", "http://+:5050"]
    volumes:
      - ./ServicesDashboard:/app
      - /app/bin
      - /app/obj
    depends_on:
      database:
        condition: service_healthy

  frontend:
    platform: linux/amd64
    build:
      context: ./services-dashboard-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./services-dashboard-frontend:/app
      - /app/node_modules
    environment:
      # Leave empty to use Vite proxy configuration
      - VITE_API_BASE_URL=
      - VITE_API_URL=/api
    command: ["yarn", "dev", "--", "--host", "0.0.0.0"]

volumes:
  postgres_data: