services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: servicesdashboard
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d servicesdashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

  servicesdashboard:
    build:
      context: ./ServicesDashboard
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT:-5050}:${BACKEND_INTERNAL_PORT:-5050}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${BACKEND_INTERNAL_PORT:-5050}
      - ConnectionStrings__DefaultConnection=Host=database;Database=servicesdashboard;Username=${DB_USER:-admin};Password=${DB_PASSWORD:-admin123}
      - AppSettings__DefaultOllamaBaseUrl=${OLLAMA_URL:-http://host.docker.internal:11434}
    command: ["dotnet", "watch", "run", "--urls", "http://+:${BACKEND_INTERNAL_PORT:-5050}"]
    volumes:
      - ./ServicesDashboard:/app
      - /app/bin
      - /app/obj
    depends_on:
      database:
        condition: service_healthy

  frontend:
    platform: linux/amd64
    build:
      context: ./services-dashboard-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_INTERNAL_PORT:-5173}"
    volumes:
      - ./services-dashboard-frontend:/app
      - /app/node_modules
    environment:
      # Leave empty to use Vite proxy configuration
      - VITE_API_BASE_URL=
      - VITE_API_URL=/api
    command: ["yarn", "dev", "--", "--host", "0.0.0.0", "--port", "${FRONTEND_INTERNAL_PORT:-5173}"]

volumes:
  postgres_data: