name: Basic Build Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build Backend
        working-directory: ./ServicesDashboard
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack and setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Build Frontend
        working-directory: ./services-dashboard-frontend
        run: |
          yarn install --frozen-lockfile
          yarn build