name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install frontend dependencies
        working-directory: ./services-dashboard-frontend
        run: yarn install --frozen-lockfile

      - name: Run frontend linting
        working-directory: ./services-dashboard-frontend
        run: yarn lint

      - name: Build frontend
        working-directory: ./services-dashboard-frontend
        run: yarn build

      - name: Restore backend dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build --configuration Release --no-restore

      - name: Run backend tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

  docker-build:
    name: Validate Docker Builds
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install frontend dependencies
        working-directory: ./services-dashboard-frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend for Docker
        working-directory: ./services-dashboard-frontend
        run: yarn build

      - name: Build backend Docker image (amd64 only for speed)
        uses: docker/build-push-action@v5
        with:
          context: ./ServicesDashboard
          file: ./ServicesDashboard/Dockerfile
          platforms: linux/amd64
          push: false
          tags: servicesdashboard-backend:pr-${{ github.event.pull_request.number }}

      - name: Build frontend Docker image (amd64 only for speed)
        uses: docker/build-push-action@v5
        with:
          context: ./services-dashboard-frontend
          file: ./services-dashboard-frontend/Dockerfile.prod
          platforms: linux/amd64
          push: false
          tags: servicesdashboard-frontend:pr-${{ github.event.pull_request.number }}

      - name: Docker builds successful
        run: |
          echo "✅ All Docker images built successfully!"
          echo "Backend: servicesdashboard-backend:pr-${{ github.event.pull_request.number }}"
          echo "Frontend: servicesdashboard-frontend:pr-${{ github.event.pull_request.number }}"
